### ISSUE TITLE
Shutdown from console locking up occasionally

### ISSUE THREAD

**Issue by sbuszard** [neilstephens/opendatacon#3]
When performing a console 'shutdown' the program does not always fully shut down, it intermittently gets stuck on the 'Finishing asynchronous tasks...' message and goes no further.  This only seems to be a problem when data is being generated by the simulator.  I didn't notice it happening when I had disabled data generation, and it was happening all the time when data generation was very fast.

![image](https://cloud.githubusercontent.com/assets/19275922/15200901/a1538408-182e-11e6-8a5f-587da44ec588.png)

**Comment by neilstephens** [comment]
Thanks for raising this one. I was vaguely aware there was an issue, but I was procrastinating looking at it because it was only on shutdown, and when I was patient enough to wait it always eventually shutdown cleanly.

It's fixed it in commit 2c962f2d80b1865ee51404a33ede0658f76c74f6 . See the commit text for details if you're interested.
