### ISSUE TITLE
WebUI Causes shutdown to delay

### ISSUE THREAD

**Issue by agilbett** [neilstephens/opendatacon#4]
When running example non-demand and the WebUI is open in a browser the shutdown is very slow. It hangs at:
`
odc> shutdown 
Disabling user interfaces... `
for a very long time.

Interestingly a refresh of the WebUI causes the process to quit cleanly.

In addition to that if you try to kill the process it dies messily with the following error:
`Disabling user interfaces... 
Fatal error in GNU libmicrohttpd daemon.c:4153: Failed to join a thread

Disabling user interfaces... 
Fatal error in GNU libmicrohttpd daemon.c:4153: Failed to join a thread

Disabling user interfaces... 
Fatal error in GNU libmicrohttpd daemon.c:4153: Failed to join a thread

Disabling user interfaces... 
Fatal error in GNU libmicrohttpd daemon.c:4153: Failed to join a thread

Disabling user interfaces... 
Fatal error in GNU libmicrohttpd daemon.c:4153: Failed to join a thread

Disabling user interfaces... 
Fatal error in GNU libmicrohttpd daemon.c:4153: Failed to join a thread

Disabling user interfaces... 
Fatal error in GNU libmicrohttpd daemon.c:4153: Failed to join a thread

Disabling user interfaces... 
Fatal error in GNU libmicrohttpd daemon.c:4153: Failed to join a thread

Disabling user interfaces... 
Fatal error in GNU libmicrohttpd daemon.c:4153: Failed to join a thread

Disabling user interfaces... 
Fatal error in GNU libmicrohttpd daemon.c:4153: Failed to join a thread

Disabling user interfaces... 
Segmentation fault
`

Good Luck
Andrew

**Comment by neilstephens** [comment]
Thanks Andrew,

Not sure what the delay is in microhttpd yet, but I will add a guard to prevent the signal handler from calling the shutdown routine multiple times. I think that will fix the resulting mess.

Cheers,
Neil.

**Comment by neilstephens** [comment]
commit 067b300e46cbfb16450daa47019a61f2185b3090 is a fix for shutdown being called multiple times. As for the microhttpd hang; since all opendatacon does is turn off the http server by calling MHD_stop_daemon(), I think it's definitely a problem in the library. I found these issues for old versions of microhttpd that match your description:
https://lists.gnu.org/archive/html/libmicrohttpd/2014-04/msg00017.html
https://gnunet.org/bugs/view.php?id=1901
One of those issues even matches your point about connecting to the server whilst hung gets it to exit.

Hopefully upgrading to a newer libmicrohttpd will fix the problem, but either way I'll close this issue because there's nothing left to do in opendatacon that might help.

Cheers,
Neil.
