### ISSUE TITLE
Microhttpd fails with alot of open filehandles 

### ISSUE THREAD

**Issue by neilstephens** [neilstephens/opendatacon#80]
[2020-08-27 13:17:15.945] [opendatacon] [critical] This is opendatacon version '1.3.0 g07208b6(268 ahead) dirty'
[2020-08-27 13:17:15.945] [opendatacon] [critical] Console level set to error
[2020-08-27 13:17:15.945] [opendatacon] [critical] Log level set to debug
Warning: MHD_USE_THREAD_PER_CONNECTION must be used only with MHD_USE_INTERNAL_POLLING_THREAD. Flag MHD_USE_INTERNAL_POLLING_THREAD was added. Consider setting MHD_USE_INTERNAL_POLLING_THREAD explicitly.
Failed to create inter-thread communication channel: Too many open files
odc> [2020-08-27 13:17:17.738] [WebUI] [error] Failed to start microhttpd daemon. MHD_start_daemon() returned nullptr

**Comment by neilstephens** [comment]
This happens when running configs that open ALOT of file handles. It should be on the roadmap to change the WebUI backend to a more modern async, or at least re-entrant library. We might have to live with it until then...

**Comment by cpp-rakesh** [comment]
With VPRN 70 (with web port)
1. microhttpd failed to create the tcp port because of lack of file descriptors available.

lsof: WARNING: can't stat() fuse.xrdp-chansrv file system /home/neil/thinclient_drives
      Output information may be incomplete.
**117373**

With VPRN 80 (with web port)
lsof: WARNING: can't stat() fuse.xrdp-chansrv file system /home/neil/thinclient_drives
      Output information may be incomplete.
**113561**

As we can see on the same machine we have 3812 extra file handlers in VPRN70, that is what causing the issue of microhttpd failure

**Comment by neilstephens** [comment]
We don't use libmicrohttpd anymore
